name: Jobs Dépendants

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: echo "Compilation terminée !"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Tests unitaires
        run: echo "Tests exécutés post compilation."
