name: Variables d'Environnement

on:
  push:

jobs:
  show-message:
    runs-on: ubuntu-latest
    env:
      MESSAGE: "Déploiement réussi"
    steps:
      - name: Afficher le message
        run: echo "$MESSAGE"
